// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5dYW2loq0k6XVRiLeelZpcegxBztb-w',
    appId: '1:392946189770:web:a894b82bef9b3ae24bbb33',
    messagingSenderId: '392946189770',
    projectId: 'bloquepantalla',
    authDomain: 'bloquepantalla.firebaseapp.com',
    storageBucket: 'bloquepantalla.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKalIVJKaiUnZClnnAIrv7ZSXzxJ134I',
    appId: '1:392946189770:android:11775aa5d4f2654d4bbb33',
    messagingSenderId: '392946189770',
    projectId: 'bloquepantalla',
    storageBucket: 'bloquepantalla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lu_YgtViV3Tn8mduX31woAz5a34yfiA',
    appId: '1:392946189770:ios:e3d1daa33934f34b4bbb33',
    messagingSenderId: '392946189770',
    projectId: 'bloquepantalla',
    storageBucket: 'bloquepantalla.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8lu_YgtViV3Tn8mduX31woAz5a34yfiA',
    appId: '1:392946189770:ios:e3d1daa33934f34b4bbb33',
    messagingSenderId: '392946189770',
    projectId: 'bloquepantalla',
    storageBucket: 'bloquepantalla.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV5dYW2loq0k6XVRiLeelZpcegxBztb-w',
    appId: '1:392946189770:web:11e675dda3aee9214bbb33',
    messagingSenderId: '392946189770',
    projectId: 'bloquepantalla',
    authDomain: 'bloquepantalla.firebaseapp.com',
    storageBucket: 'bloquepantalla.firebasestorage.app',
  );
}
